// Command mixer is the audio demo a game would recognise: a three-minute music
// track streaming under short one-shots that overlap it, each set on its own
// Bus, driven from the keyboard, with the live Voice table on screen.
//
//	go run ./cmd/sound/mixer
//
// Every other sound demo here isolates one decision and prints it to a console.
// This one puts the two residency tiers in one mixer at the same time, which is
// the ordinary case, and it opens a window — because a demo you can drive is
// worth one, and because cog's input binds to gogpu's window, so a demo with no
// window has no keyboard.
//
// # What it is evidence for
//
// **The streamed tier exists and nothing has to ask for it.** The music is
// assets/music/pleasant-moments.ogg: 176.181 s of stereo 44.1 kHz, 2.7 MiB
// encoded and 59.3 MiB decoded, a ratio of 21.8x. otosound's and jssound's
// DecodedClipLimit defaults to 512 KiB — 1.49 s of stereo 44.1 kHz — so the
// track is three orders of magnitude over the line and streams with no
// configuration at all. The one-shot beside it is the 1.1 s cut of the same
// recording, which is well under the limit and is decoded once and held. Both
// are played through one call, and see play for why there is no branch there.
//
// **Voices overlap, and the cap is a band rather than a weight.** The engine is
// composed with MaxVoices at 12, and B records sixteen plays into a single
// tick, so the cap takes at least four of them in the flush that starts the
// rest - five while the music holds a slot of its own. The music is at
// Priority 1 and the one-shots at 0, so the music is never among them however
// loud the burst is; that is cmd/sound/crowd's subject, shown here as the
// thing it actually protects.
//
// **A Bus volume moves one set of rows and not the other.** Each row's
// audibility is drawn as a bar, so turning the music Bus down moves one bar and
// leaves eleven where they were. That is the settings-screen case SetBus exists
// for, and it is the first thing a player notices in a real game.
//
// **Nothing on screen is the demo's own idea of what is happening.** Every
// number in the table is read back off kernel.Read[*sound.Voices],
// [*sound.Buses], [*sound.Clips] and [*sound.Device] — what the engine derived,
// not what this program commanded. Run it on a machine with no sound card and
// the Device row says not ready while every playhead keeps moving, because a
// Voice's clock is the engine's rather than the device's.
//
// # Keys
//
//	M          music on / off
//	SPACE      fire one one-shot; 2 is the same key by another name
//	1 2 3      fire one one-shot at pitch 0.70 / 1.00 / 1.45
//	B          fire sixteen at once, which is more Voices than the engine has
//	S          suspend / resume the music Voice on its own
//	LEFT RIGHT seek the music by -10 s / +10 s
//	[ ]        music Bus volume down / up
//	, .        effects Bus volume down / up
//	- =        master down / up
//	P          pause / resume the engine
//	ESC        quit
//
// In a browser the keys reach the demo only once the canvas has focus: gogpu
// binds keydown on the canvas element rather than on the document, which is why
// cmd/web/index.html gives it a tabindex and focuses it. And a page makes no
// sound at all until a gesture resumes its AudioContext, so the Device row
// reads not-ready until the first click. jssound installs that listener itself;
// the demo only says which state it is in.
package main

import (
	"fmt"
	"os"
	"os/signal"

	_ "embed"

	"github.com/dvoyni/cog-examples/internal/assets"
	"github.com/dvoyni/cog-examples/internal/permanentfs"
	"github.com/dvoyni/cog-examples/internal/soundbackend"
	"github.com/dvoyni/cog/bundles/canvas"
	"github.com/dvoyni/cog/bundles/canvas/canvasplugin"
	"github.com/dvoyni/cog/bundles/input"
	"github.com/dvoyni/cog/bundles/input/inputplugin"
	"github.com/dvoyni/cog/extensions/gogpu"
	"github.com/dvoyni/cog/extensions/gogpu/gogpuplugin"
	"github.com/dvoyni/cog/kernel"
	cogassets "github.com/dvoyni/cog/libs/assets"
	"github.com/dvoyni/cog/libs/config"
	"github.com/dvoyni/cog/libs/m"
	"github.com/dvoyni/cog/slots/app"
	"github.com/dvoyni/cog/slots/app/appplugin"
	"github.com/dvoyni/cog/slots/gfx"
	"github.com/dvoyni/cog/slots/gfx/gfxplugin"
	"github.com/dvoyni/cog/slots/sound"
	"github.com/dvoyni/cog/slots/sound/soundplugin"
	"github.com/dvoyni/cog/slots/storage"
	"github.com/dvoyni/cog/slots/storage/storageplugin"
)

// effectOgg is the one-shot, embedded the way every other sound demo here
// embeds it: assets/ is generated by cmd/prepare-assets from a manifest of
// models, and one second of audio should not have to join it. See
// ATTRIBUTION.md beside this file.
//
// The music is not embedded, and must not be: it is 2.7 MiB of the binary that
// would then also be 59.3 MiB of process memory the moment anything played it.
// It is named by a path and read through the assets mount instead.
//
//go:embed pianoroll.ogg
var effectOgg []byte

// musicPath is the streamed Clip, named exactly as the repository spells it.
// The mount internal/assets builds presents the assets/ prefix on both
// platforms, so this is one string for the desktop and the browser.
const musicPath = "assets/music/pleasant-moments.ogg"

// The two Buses this demo declares. Neither is Master, which is deliberate:
// Master is the default Bus rather than a global trim — a Bus's volume folds
// into the Voices on that Bus and nowhere else — so a game that declares Buses
// has nothing left on Master and its master slider is a scale it applies to the
// Buses it declared. cmd/sound/buses is the demo that argues that point; this
// one just lives with it, in applyVolumes.
const (
	BusMusic   sound.Bus = 1
	BusEffects sound.Bus = 2
)

// maxVoices is the whole engine's Voice table, made small enough that one
// press of B - sixteen plays in one tick - overruns it, which is the only way
// to reach the cap here: a one-shot lasts 1.1 s, so no rate of pressing a fire
// key keeps twelve of them alive at once.
const maxVoices = 12

// The logical viewport the HUD is laid out in. The window is fitted to it, so
// the table keeps its proportions at any window size.
const (
	screenWidth  = 960
	screenHeight = 600
)

// The canvas layers. The backdrop clears the frame and carries the audibility
// bars; the HUD is the text over them.
const (
	layerBackdrop canvas.Layer = -100
	layerHUD      canvas.Layer = 0
)

func main() {
	// storage mounts nothing by default, and the music lives in the repository
	// rather than beside the executable, which `go run` builds into a temporary
	// directory - so the demo mounts assets/ explicitly and refuses to start
	// without it.
	storageConfig, err := assets.Config(storage.Config{})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	cfg := map[kernel.PluginName]any{
		storage.Name: storageConfig,
		// MaxVoices is the one number a game tunes: how many sounds it wants at
		// once. Twelve is small so that one press of B overruns it; the memory
		// follows from what is played, and nothing here says a word about which
		// tier anything lands in.
		sound.Name: sound.Config{}.WithMaxVoices(maxVoices),
		gogpu.Name: gogpu.Config{}.
			WithTitle("cog examples: sound mixer").
			WithSize(screenWidth, screenHeight),
	}
	permanentfs.Configure(cfg)
	soundbackend.Configure(cfg)
	// Last of the contributors, so every plugin an override may name is in the
	// map by now: --cog.sound.MaxVoices=64, and so on.
	cfg = config.Inject(cfg)

	// mixer is last because it records into the queues the plugins before it
	// declare.
	demo := newMixer()
	plugins := []kernel.Plugin{
		storageplugin.New(),
		permanentfs.New(), // storage's PermanentFS Adapter for this platform
		inputplugin.New(),
		appplugin.New(),
		gfxplugin.New(),
		canvasplugin.New(),
		soundplugin.New(),
		soundbackend.New(), // sound's Backend Adapter for this platform
		gogpuplugin.New(),
		demo,
	}

	engine := kernel.New(cfg).WithPlugins(plugins...)
	// Ctrl+C asks the host to leave its loop, the same way closing the window
	// does.
	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	go func() {
		<-interrupt
		engine.Quit()
	}()
	if err := engine.Run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// Name is the demo plugin's name.
const Name kernel.PluginName = "mixer"

type viewportHandler kernel.Subscription[app.WindowSizeChangeEvent]
type tickHandler kernel.Subscription[app.UpdateEvent]
type keyHandler kernel.Subscription[input.KeyEvent]

// Control is the demo's own resource, and it carries one bool.
//
// It is a resource rather than a field on the plugin because two handlers write
// it, and the kernel publishes every event on its own goroutine: the per-tick
// handler and the input.KeyEvent handler below would otherwise be a data race
// the kernel cannot see, which is exactly what a resource is for.
//
// Two handlers are needed because app.TimePause stops app.UpdateEvent. A demo
// that read its pause key from a per-tick handler could pause and could never
// resume, because the tick that would read the second press never comes.
// input.KeyEvent is published from input's Apply, which gogpu runs once a frame
// whether or not the tick source is paused - pause stops the tick and not the
// frame.
type Control struct {
	// EnginePaused is what the pause key has asked for, which is one tick ahead
	// of what app's tick source has done about it: the tick that sees this set
	// draws the paused frame first and pauses at the end of itself, so the
	// frame left frozen on screen is the one that says so.
	EnginePaused bool
}

// clip is one of the demo's two sounds and everything it knows about either:
// the ClipRef, the name to print, and the Bus it belongs on.
//
// It is a table rather than two fields so that the play below has one body, and
// so that labelling a row in the live Voice table is a lookup rather than a
// chain of comparisons. ClipRef is opaque by design - there is no exported way
// to read a path back out of one - so a game that wants to name its sounds on
// screen keeps its own table, which is what this is.
type clip struct {
	ref   sound.ClipRef
	label string
	bus   sound.Bus
}

// The two entries of that table.
const (
	clipMusic = iota
	clipEffect
	clipCount
)

// mixer is the demo plugin: the gameplay and the HUD, in one type because a
// demo is self-contained.
type mixer struct {
	sounds [clipCount]clip

	// voice is the music's Voice, or NoVoice while the music is off. It is the
	// only handle the demo keeps: a one-shot is fired and forgotten, which is
	// what makes it a one-shot.
	voice sound.Voice

	// The three slider positions, which are the demo's own state because a
	// settings screen's sliders are. What they produce is read back off
	// sound.Buses rather than remembered; see applyVolumes.
	master, musicMix, effectsMix float32

	ticks int
	// fired counts every one-shot recorded, including the ones the cap stole
	// before they ever sounded. It is on screen beside the live Voice count so
	// the two can be compared: after a burst the difference is what the cap
	// took.
	fired int
}

func newMixer() *mixer {
	return &mixer{master: 0.85, musicMix: 0.75, effectsMix: 0.80}
}

// The demo is a plugin and nothing more. gogpu is the PluginHost here - it owns
// the window and so the blocking loop - which is the whole difference between
// this demo and the four beside it that supply their own app.MainLoop.
var _ kernel.Plugin = (*mixer)(nil)

func (p *mixer) Name() kernel.PluginName { return Name }

// Dependencies names every plugin whose resources this demo locks. app is not
// among them: subscribing to app.UpdateEvent needs no dependency, because an
// event nobody publishes is simply never delivered.
func (p *mixer) Dependencies() []kernel.PluginName {
	return []kernel.PluginName{canvas.Name, gfx.Name, input.Name, sound.Name, storage.Name}
}

func (p *mixer) Register(registrar *kernel.Registrar, _ any) error {
	p.sounds = [clipCount]clip{
		clipMusic: {
			// ClipWithResource names a Clip by a storage path. The bytes are
			// read inside sound's flush, on the tick the Play that needs them
			// was recorded - so the first tick of this demo eats a 2.7 MiB read
			// and nothing after it does.
			ref:   sound.ClipWithResource(musicPath),
			label: "music",
			bus:   BusMusic,
		},
		clipEffect: {
			// ClipWithBytes names a Clip by encoded Ogg the caller already
			// holds. The Blob is built once, here, because a fresh one every
			// call would name an asset nothing can ask for twice.
			ref:   sound.ClipWithBytes(cogassets.NewBlob(effectOgg)),
			label: "one-shot",
			bus:   BusEffects,
		},
	}
	registrar.InitResource(&Control{})
	registrar.Subscribe[viewportHandler](setViewport)
	registrar.Subscribe[tickHandler](p.tick)
	registrar.Subscribe[keyHandler](p.onKey)
	return nil
}

// setViewport fits the logical screen inside the window, swapping the axes when
// the window is taller than it is wide.
func setViewport() (kernel.Lock, kernel.Observe[app.WindowSizeChangeEvent]) {
	var setDesiredViewport func(kernel.Kernel, gfx.SetDesiredViewportRequest) gfx.SetDesiredViewportResponse
	return func(access kernel.ResourceAccess) {
			setDesiredViewport = access.Uses[gfx.SetDesiredViewportCmd]()
		}, func(k kernel.Kernel, event app.WindowSizeChangeEvent) {
			if event.Width <= 0 || event.Height <= 0 {
				return
			}
			width, height := float32(screenWidth), float32(screenHeight)
			if event.Height > event.Width {
				width, height = height, width
			}
			setDesiredViewport(k,
				gfx.SetDesiredViewportRequest{Mode: gfx.ViewportFit, Width: width, Height: height})
		}
}

// onKey is the half of the keyboard that has to work when the tick source has
// stopped: the pause key, and the one that leaves.
//
// It declares no resource lock of its own beyond Control, because everything
// else it does is a command. Neither app.TimeCmd nor app.QuitCmd declares any
// lock at all, so folding them in costs this handler nothing and it never
// contends with the tick it may be interrupting.
func (p *mixer) onKey() (kernel.Lock, kernel.Observe[input.KeyEvent]) {
	var control kernel.Write[*Control]
	var time func(kernel.Kernel, app.TimeRequest) app.TimeResponse
	var quit func(kernel.Kernel, app.QuitRequest) app.QuitResponse
	return func(access kernel.ResourceAccess) {
			control = access.GetWrite[*Control]()
			time = access.Uses[app.TimeCmd]()
			quit = access.Uses[app.QuitCmd]()
		}, func(k kernel.Kernel, event input.KeyEvent) {
			if !event.Down {
				return
			}
			switch event.Key {
			case input.KeyEscape:
				quit(k, app.QuitRequest{})
			case input.KeyP:
				c := control.Get()
				if c.EnginePaused {
					// Resuming is done here and now, because there is no tick
					// left to defer it to.
					c.EnginePaused = false
					time(k, app.TimeRequest{Action: app.TimeResume})
					return
				}
				// Pausing is deferred to the tick that is still coming, so that
				// the last frame composed before the ticks stop is the one
				// carrying the paused banner. A pause taken here would freeze
				// the previous frame instead, and a window that says nothing
				// about why it stopped moving reads as hung.
				c.EnginePaused = true
			}
		}
}

// tick is the demo: read the keyboard, record what it asked for, draw what the
// engine made of it.
//
// Its lock set is a write on the two queues it records into, a write on its own
// Control, and reads on the four sound views it reports. It writes no Voice
// state of its own - where a playhead stands, how loud a Voice ended up and how
// many of them are live are sound's to compute, and asking is a read.
func (p *mixer) tick() (kernel.Lock, kernel.Observe[app.UpdateEvent]) {
	var queue kernel.Write[*sound.Queue]
	var ops kernel.Write[*canvas.OpQueue]
	var control kernel.Write[*Control]
	var voices kernel.Read[*sound.Voices]
	var buses kernel.Read[*sound.Buses]
	var clips kernel.Read[*sound.Clips]
	var device kernel.Read[*sound.Device]
	var keys kernel.Read[*input.State]
	var time func(kernel.Kernel, app.TimeRequest) app.TimeResponse
	return func(access kernel.ResourceAccess) {
			queue = access.GetWrite[*sound.Queue]()
			ops = access.GetWrite[*canvas.OpQueue]()
			control = access.GetWrite[*Control]()
			voices = access.GetRead[*sound.Voices]()
			buses = access.GetRead[*sound.Buses]()
			clips = access.GetRead[*sound.Clips]()
			device = access.GetRead[*sound.Device]()
			keys = access.GetRead[*input.State]()
			time = access.Uses[app.TimeCmd]()
		}, func(k kernel.Kernel, _ app.UpdateEvent) {
			q := queue.Get()
			live := voices.Get()
			paused := control.Get().EnginePaused

			p.ticks++
			if p.ticks == 1 {
				// The music starts by itself, because a demo about music
				// playing under things should be playing music when it opens.
				p.startMusic(q)
			}
			p.hotkeys(q, keys.Get(), live)
			p.applyVolumes(q)

			p.draw(ops.Get(), live, buses.Get(), clips, device.Get(), paused)

			if paused {
				// Last thing in the tick, and after the frame is recorded: the
				// canvas flush that consumes what draw just wrote runs later in
				// this same tick, and app.TimePause stops the ticks that come
				// after this one rather than this one.
				time(k, app.TimeRequest{Action: app.TimePause})
			}
		}
}

// hotkeys turns this tick's keyboard into operations on the Queue.
//
// Everything here is JustPressed or Pressed on input.State rather than a
// subscription, because a key that only matters while the engine is ticking is
// simplest read at the tick. The two that must survive a stopped tick source
// are in onKey.
func (p *mixer) hotkeys(q *sound.Queue, keys *input.State, live *sound.Voices) {
	if keys == nil {
		return
	}

	// Whether the music is on is asked of the live view rather than read off
	// the handle. A handle outlives its Voice - a Clip that failed to load ends
	// the Voice it was played on - and a toggle that trusted the handle would
	// spend its first press stopping a Voice that was already gone.
	if keys.JustPressed(input.KeyM) {
		if _, on := live.Info(p.voice); on {
			q.Stop(p.voice)
			p.voice = sound.NoVoice
		} else {
			p.startMusic(q)
		}
	}

	// Every firing key is an edge and nothing else: one press, one sound. A
	// deliberate keypress lasts 100-200 ms, which is six to twelve ticks at
	// 60 Hz, so anything that counted ticks while the key was down would have
	// no gesture that fired exactly once - and one sound per press is what a
	// fire button is.
	if keys.JustPressed(input.KeySpace) || keys.JustPressed(input.Key2) {
		p.fire(q, 1)
	}
	if keys.JustPressed(input.Key1) {
		p.fire(q, lowPitch)
	}
	if keys.JustPressed(input.Key3) {
		p.fire(q, highPitch)
	}

	// B is the one gesture that outruns the table, and it is one press rather
	// than a held key: burstSize plays recorded into a single tick, which is
	// more Voices than exist. It is also an ordinary game moment - an explosion
	// is a dozen sounds in one frame - and it is the only way to reach the cap
	// here, because a one-shot lasts 1.1 s and nobody presses a key twelve
	// times inside it. cmd/sound/crowd is the same shape with the numbers
	// written down.
	if keys.JustPressed(input.KeyB) {
		for i := range burstSize {
			p.fire(q, burstPitches[i%len(burstPitches)])
		}
	}

	// Suspending one Voice stops its playhead without ending it, and resumes it
	// on the same sample. It is the demo's answer to "what does the paused
	// column mean": the music's row freezes while every one-shot beside it goes
	// on moving.
	if keys.JustPressed(input.KeyS) {
		if info, ok := live.Info(p.voice); ok {
			q.SetVoice(p.voice, sound.Params{Paused: m.Some(!info.Params.Paused.Or(false))})
		}
	}

	if keys.JustPressed(input.KeyLeft) {
		p.seek(q, live, -seekStep)
	}
	if keys.JustPressed(input.KeyRight) {
		p.seek(q, live, seekStep)
	}

	p.master = slide(p.master, keys, input.KeyMinus, input.KeyEqual)
	p.musicMix = slide(p.musicMix, keys, input.KeyLeftBracket, input.KeyRightBracket)
	p.effectsMix = slide(p.effectsMix, keys, input.KeyComma, input.KeyPeriod)
}

// The hotkeys' numbers.
const (
	// burstSize is how many one-shots B records in one tick. Sixteen against a
	// table of twelve, so the cap takes at least four of them in the same
	// flush that starts the rest - five while the music holds a slot - and the
	// music, a priority band above all of them, is never among them however
	// loud the burst is.
	burstSize = 16
	// The pitches keys 1 and 3 fire at. The Clip is the same one every time:
	// there is no Ogg encoder in this tree, and a rate change is a real,
	// audible second sound rather than an invented asset.
	lowPitch  = 0.70
	highPitch = 1.45
	// seekStep is how far one arrow press moves the music, in seconds. Seek is
	// block-accurate rather than sample-accurate, which is why ten seconds
	// rather than ten milliseconds: the point on screen is that the playhead
	// lands where it was asked, not how exactly.
	seekStep = 10
	// volumeStep is how much a held volume key moves a slider per tick. A
	// slider should move while it is held rather than jump on the edge, so this
	// one has no repeat delay - but it is slow enough to aim: about half of
	// unity a second at 60 Hz, so the whole range takes two seconds and the
	// 100-200 ms of a tap is a nudge of five to ten hundredths rather than a
	// leap.
	volumeStep = 0.008
)

// burstPitches is what a burst's one-shots are spread across, so sixteen plays
// of one Clip are sixteen distinguishable sounds rather than one very loud one.
// Pitch is the only dimension available: there is no Ogg encoder in this tree,
// so varying the rate of the Clip that is here beats vendoring assets that are
// not.
var burstPitches = [...]float32{0.70, 0.85, 1.00, 1.20, 1.45}

// slide moves one slider while its keys are held, clamped to [0, 1].
//
// A slider is the one thing here that should move while a key is down rather
// than jump on its edge, which is why it reads Pressed and the firing keys read
// JustPressed. The edge is taken as well, and only because of the degenerate
// case: a press and its release inside one frame's input flush leave the key
// never held on any tick, so a slider that read Pressed alone would refuse to
// move at all for a tap that short. Down-or-just-pressed is one step per tick
// either way, so nothing is counted twice.
func slide(value float32, keys *input.State, down, up input.Key) float32 {
	if keys.Pressed(down) || keys.JustPressed(down) {
		value -= volumeStep
	}
	if keys.Pressed(up) || keys.JustPressed(up) {
		value += volumeStep
	}
	return max(0, min(1, value))
}

// startMusic plays the streamed Clip, looping, a priority band above everything
// else in the engine.
func (p *mixer) startMusic(q *sound.Queue) {
	p.voice = p.play(q, clipMusic, sound.Params{
		Volume: m.Some[float32](1),
		Loop:   m.Some(true),
		// A band and not a weight. The music is about to be the quietest thing
		// in the engine as soon as anyone turns its Bus down, and a cap that
		// ranked on loudness alone would take it first, every burst.
		Priority: m.Some(1),
	})
}

// fire records one one-shot at a pitch. It keeps no handle: a one-shot ends by
// itself when its Clip runs out, and a Voice that ever existed is observable
// exactly once - it is in the live view now, or its ending has already fired.
func (p *mixer) fire(q *sound.Queue, pitch float32) {
	p.play(q, clipEffect, sound.Params{
		Volume:   m.Some[float32](0.9),
		Pitch:    m.Some(pitch),
		Priority: m.Some(0),
	})
	p.fired++
}

// play starts one Voice on one of the demo's two Clips, on that Clip's own Bus.
//
// # Where the branch on the residency tier would go, and why there is none
//
// This is the one call both Clips are played through, so this is where a reader
// looking for "if it is the long one, do something else" would look. There is
// nothing here, and there is nothing anywhere else either.
//
// One of these Clips is 176 s and 59.3 MiB decoded, so it is streamed: a
// decoder and a read-ahead ring per Voice, a few thousand frames at a time. The
// other is 1.1 s and 190 KiB decoded, so it is decoded once and every Voice
// shares the samples. Which tier a Clip landed in is decided inside the
// Adapter, from a decoded size computed before anything is decoded, against a
// DecodedClipLimit this demo never names — and sound itself never learns the
// answer, which is why sound.Config has one number in it and not two.
//
// A game cannot ask, and this is what that is worth: both tiers report the same
// duration, channels, rate and loop region through ClipInfoOf; both are played
// by Play, sought by Seek, suspended by Params.Paused, folded into a Bus and
// stolen by the cap identically. Preload is the one verb whose promise is
// deliberately weaker than a caller might want — it promises residency, not
// that the next Play is free, because a streamed Clip's first Play still opens
// a decoder — and that weaker promise is the same promise for both.
func (p *mixer) play(q *sound.Queue, which int, params sound.Params) sound.Voice {
	c := p.sounds[which]
	params.Bus = m.Some(c.bus)
	return q.Play(c.ref, 0, params)
}

// seek moves the music by a number of seconds, reading where it is from the
// live view rather than from a clock of the demo's own. That is the whole
// difference between showing Seek work and asserting that it did: the playhead
// the next frame draws is sound's answer, not this program's arithmetic.
func (p *mixer) seek(q *sound.Queue, live *sound.Voices, by float32) {
	info, ok := live.Info(p.voice)
	if !ok {
		return
	}
	at := info.Playhead + by
	if at < 0 {
		at = 0
	}
	if info.Duration > 0 && at >= info.Duration {
		at = info.Duration - 1
	}
	q.Seek(p.voice, at)
}

// applyVolumes records what the three sliders currently mean.
//
// The master slider is a scale over the two declared Buses rather than a
// SetBus on Master, and that is not a workaround. Buses are flat and a Bus's
// volume folds into the Voices on that Bus and nowhere else, so Master is the
// default Bus - where every Voice in a game that declared none lands - and not
// a trim above the others. Nothing in this demo is on Master, so a SetBus on it
// would move nothing at all, which is precisely what cmd/sound/buses exists to
// show. A game's master slider is this: one number the game owns, applied to
// the Buses the game declared.
//
// Recording it every tick costs nothing. A Bus volume coalesces within the
// tick, and the fold skips any Voice whose bus gain did not move, so a value
// that has not changed re-emits nothing across the seam.
func (p *mixer) applyVolumes(q *sound.Queue) {
	q.SetBus(BusMusic, p.master*p.musicMix)
	q.SetBus(BusEffects, p.master*p.effectsMix)
}

// labelFor names the Clip a live Voice is playing. ClipRefs are compared with
// Equal rather than ==, because a ref with a path is identified by that path
// whatever bytes travel beside it.
func (p *mixer) labelFor(ref sound.ClipRef) string {
	for i := range p.sounds {
		if p.sounds[i].ref.Equal(ref) {
			return p.sounds[i].label
		}
	}
	return "?"
}
