// Command orbit is the smallest cog application that makes a sound: a looping
// clip circles the listener at a constant radius, so you hear it pan from ear
// to ear, and the console prints what sound derived from where the demo put it.
//
// It needs no GPU and opens no window. app requires a MainLoop Adapter and
// gogpu is what fills it in every other demo here, so this one supplies its own
// — a plain real-time ticker, which is all a game that only makes noise needs.
//
//	go run ./cmd/sound/orbit
//
// What to listen for, and what to watch:
//
//   - The sound crosses from one ear to the other and back. That is sound's own
//     equal-power panning, transcribed from the W3C Web Audio specification, not
//     a PannerNode and not a scalar pan.
//   - audibility does not move, at all, while the azimuth sweeps the whole way.
//     That is the point of it: audibility is the gain before panning, so
//     "quietest" and "furthest away" are one policy rather than two that
//     disagree with each other on a circle. A source at a constant radius is
//     exactly as audible behind you as beside you.
//   - The playhead advances whether or not anything is audible. Run this on a
//     machine with no sound card and every number still moves, because a Voice's
//     clock is the engine's rather than the device's.
//
// Ctrl+C leaves.
package main

import (
	"fmt"
	"math"
	"os"
	"os/signal"
	"time"

	_ "embed"

	"github.com/dvoyni/cog-examples/internal/permanentfs"
	"github.com/dvoyni/cog-examples/internal/soundbackend"
	"github.com/dvoyni/cog/kernel"
	"github.com/dvoyni/cog/libs/assets"
	"github.com/dvoyni/cog/libs/config"
	"github.com/dvoyni/cog/libs/m"
	"github.com/dvoyni/cog/slots/app"
	"github.com/dvoyni/cog/slots/app/appplugin"
	"github.com/dvoyni/cog/slots/sound"
	"github.com/dvoyni/cog/slots/sound/soundplugin"
	"github.com/dvoyni/cog/slots/storage"
	"github.com/dvoyni/cog/slots/storage/storageplugin"
)

// clipOgg is the demo's one sound, embedded rather than vendored into assets/.
// assets/ is generated by cmd/prepare-assets from a manifest of models, and a
// demo that wants one sound should not have to join it — so this plays through
// sound.ClipWithBytes, which is the ClipRef form that names a run of encoded
// Ogg rather than a path. See ATTRIBUTION.md beside this file.
//
//go:embed pianoroll.ogg
var clipOgg []byte

const (
	// orbitRadius is how far the source circles the listener, in the world's
	// own units. Everything positional here is metres because the falloff below
	// says so and for no other reason: sound learns no scale.
	orbitRadius = 3
	// revolution is how long one full circle takes. Slow enough to hear the
	// image travel rather than wobble.
	revolution = 8 * time.Second
	// tickRate is the demo's fixed update rate. app owns the accumulator; this
	// is only how often the ticker wakes the loop.
	tickRate = 60
	// printEvery is how many ticks pass between console lines. Four a second is
	// enough to watch a number move and few enough to read.
	printEvery = tickRate / 4
)

func main() {
	cfg := map[kernel.PluginName]any{
		storage.Name: storage.Config{},
		sound.Name:   sound.Config{},
	}
	permanentfs.Configure(cfg)
	soundbackend.Configure(cfg)
	// Last of the contributors, so every plugin an override may name is in the
	// map by now: --cog.sound.MaxVoices=8, and so on.
	cfg = config.Inject(cfg)

	// orbit is last because it records into the queue the plugins before it
	// declare. storage is here because sound depends on it — a Clip named by a
	// path is read through it — even though this demo names its Clip by bytes.
	plugins := []kernel.Plugin{
		storageplugin.New(),
		permanentfs.New(),
		appplugin.New(),
		soundplugin.New(),
		soundbackend.New(), // sound's Backend Adapter for this platform
		newOrbit(),
	}

	engine := kernel.New(cfg).WithPlugins(plugins...)
	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	go func() {
		<-interrupt
		engine.Quit()
	}()
	if err := engine.Run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// Name is the demo plugin's name.
const Name kernel.PluginName = "orbit"

// OrbitMainLoop is the Adapter through which this demo fills app's MainLoop
// Port. A sound demo wants no window, and app's loop has to come from
// somewhere, so the demo is its own platform.
type OrbitMainLoop kernel.Adapter[app.MainLoopPort]

// UpdateOnTick is the demo's one subscription: move the source, then read back
// what sound made of it.
type UpdateOnTick kernel.Subscription[app.UpdateEvent]

// orbit is the demo plugin: the gameplay, the MainLoop Adapter and the Host, in
// one type because a demo is self-contained and because all three are about the
// same handful of lines.
type orbit struct {
	loop    app.Loop
	quit    chan struct{}
	clip    sound.ClipRef
	voice   sound.Voice
	elapsed float64
	ticks   int
}

func newOrbit() kernel.Plugin { return &orbit{quit: make(chan struct{})} }

var (
	_ kernel.Plugin     = (*orbit)(nil)
	_ kernel.PluginHost = (*orbit)(nil)
	_ app.MainLoop      = (*orbit)(nil)
)

func (o *orbit) Name() kernel.PluginName { return Name }

// Dependencies names sound, whose resources this demo locks. app is not among
// them: subscribing to app.UpdateEvent needs no dependency, because an event
// nobody publishes is simply never delivered.
func (o *orbit) Dependencies() []kernel.PluginName {
	return []kernel.PluginName{sound.Name}
}

func (o *orbit) Register(registrar *kernel.Registrar, _ any) error {
	o.clip = sound.ClipWithBytes(assets.NewBlob(clipOgg))
	registrar.ProvideAdapter[OrbitMainLoop](app.MainLoop(o))
	registrar.Subscribe[UpdateOnTick](o.updateOnTick)
	return nil
}

func (o *orbit) Start(kernel.Executioner) error { return nil }
func (o *orbit) Stop(kernel.Executioner)        {}

// Attach keeps the Loop app hands over. It arrives from app's Start, before Run
// and before any frame.
func (o *orbit) Attach(loop app.Loop) { o.loop = loop }

// Quit asks Run to leave its loop. The engine calls it from a goroutine that is
// not the one inside Run and may call it more than once, so the close is
// guarded by a select rather than done outright.
func (o *orbit) Quit() {
	select {
	case <-o.quit:
	default:
		close(o.quit)
	}
}

// ClipboardWrite refuses. There is no window and no clipboard to write to, and
// a demo that silently dropped the text would be worse than one that says so.
func (o *orbit) ClipboardWrite(string) error {
	return fmt.Errorf("orbit: no clipboard without a window")
}

// Run is the platform loop this demo stands in for: wake at the tick rate, hand
// app the real seconds that passed, and let its accumulator decide how many
// updates that is. Nothing is drawn, so Render is never called.
func (o *orbit) Run(k kernel.Executioner) error {
	if err := o.loop.Init(k); err != nil {
		return err
	}
	defer o.loop.Quit(k)

	fmt.Println("orbit: a looping clip circles the listener at", orbitRadius, "units.")
	fmt.Println("       listen for the pan; watch audibility stay put. Ctrl+C leaves.")
	fmt.Println()

	ticker := time.NewTicker(time.Second / tickRate)
	defer ticker.Stop()
	last := time.Now()
	for {
		select {
		case <-o.quit:
			return nil
		case now := <-ticker.C:
			dt := now.Sub(last).Seconds()
			last = now
			o.loop.Frame(k, dt)
		}
	}
}

// updateOnTick is the whole of the demo's gameplay: start the Voice on the
// first tick, move it every tick after, and print what sound derived from it.
//
// Its lock set is a write on the queue and reads on the two views it reports.
// It writes no Voice state of its own: where a playhead stands and how loud a
// source ended up are sound's to compute, and asking is a read.
func (o *orbit) updateOnTick() (kernel.Lock, kernel.Observe[app.UpdateEvent]) {
	var queue kernel.Write[*sound.Queue]
	var voices kernel.Read[*sound.Voices]
	var device kernel.Read[*sound.Device]
	return func(access kernel.ResourceAccess) {
			queue = access.GetWrite[*sound.Queue]()
			voices = access.GetRead[*sound.Voices]()
			device = access.GetRead[*sound.Device]()
		}, func(_ kernel.Kernel, event app.UpdateEvent) {
			q := queue.Get()
			o.elapsed += event.Dt

			if o.voice == sound.NoVoice {
				// The listener stays at the origin facing -Z with +Y up, which
				// is the W3C default listener and cog's own axes. A 2D game
				// would turn it a quarter turn about X here, because a plane
				// containing the listener's up axis can only pan hard left or
				// hard right.
				q.SetListener(sound.ListenerParams{Position: m.Some(m.Vec3{})})
				o.voice = q.Play(o.clip, 0, sound.Params{
					Volume:   m.Some[float32](0.8),
					Loop:     m.Some(true),
					Position: m.Some(o.at(0)),
					// Ref is the world's scale, not W3C's 1. Left at 1 a source
					// three units out would arrive 9.5 dB down for no reason the
					// game ever stated; at the orbit's own radius the circle
					// sits at unity and the pan is the only thing moving.
					Falloff: m.Some(sound.Falloff{
						Model:   sound.DistanceInverse,
						Ref:     orbitRadius,
						Max:     10000,
						Rolloff: 1,
					}),
				})
			} else {
				q.SetVoice(o.voice, sound.Params{Position: m.Some(o.at(o.elapsed))})
			}

			o.ticks++
			if o.ticks%printEvery == 0 {
				o.report(voices.Get(), device.Get())
			}
		}
}

// at is where the source is after elapsed seconds: a circle about the listener
// in the XZ plane, which is the horizontal plane for a listener nobody turned.
// It starts dead ahead and travels to the right.
func (o *orbit) at(elapsed float64) m.Vec3 {
	angle := 2 * math.Pi * elapsed / revolution.Seconds()
	return m.Vec3{
		X: float32(math.Sin(angle) * orbitRadius),
		Y: 0,
		Z: float32(-math.Cos(angle) * orbitRadius),
	}
}

// report prints one line of what sound derived. It reads the live Voice view
// rather than the demo's own idea of where the source is, because the whole
// point is to show what the engine made of the command.
func (o *orbit) report(live *sound.Voices, dev *sound.Device) {
	info, ok := live.Info(o.voice)
	if !ok {
		fmt.Printf("voice gone   %d/%d voices   %s\n", live.Len(), live.Cap(), deviceLine(dev))
		return
	}
	// Azimuth is not on the live view — a game's test asserts what it commanded
	// and what the engine derived, and the pan is neither. The demo knows where
	// it put the source, so it says the bearing it asked for and lets sound
	// speak for the rest.
	azimuth := math.Mod(360*o.elapsed/revolution.Seconds(), 360)
	if azimuth > 180 {
		azimuth -= 360
	}
	fmt.Printf("%s  az %+6.1f°  dist %4.2f  audibility %4.2f  head %5.2fs  %d/%d voices   %s\n",
		panBar(azimuth), azimuth, info.Distance, info.Audibility, info.Playhead,
		live.Len(), live.Cap(), deviceLine(dev))
}

// panBar draws where the image sits between the ears, so the pan is visible on
// a machine that cannot play it.
func panBar(azimuth float64) string {
	const width = 21
	slot := int(math.Round((azimuth/180 + 1) / 2 * (width - 1)))
	slot = max(0, min(width-1, slot))
	bar := []byte("L...................R")
	bar[slot] = '#'
	return string(bar)
}

// deviceLine says whether anything can be heard. A game reads Device rather
// than handling it: absent, not ready yet and lost all look the same from here,
// and the playhead advances through all three.
func deviceLine(dev *sound.Device) string {
	if !dev.Ready {
		return "device: not ready (the playhead still moves)"
	}
	return fmt.Sprintf("device: %s %d Hz", dev.Name, dev.SampleRate)
}
