package main

import (
	"fmt"
	"slices"
	"strings"
)

// attributionFile is where the rendered credits land, relative to the asset
// root.
const attributionFile = "ATTRIBUTION.md"

// renderAttribution writes the credits for the whole vendored set.
//
// It is generated rather than hand-maintained for one reason: CC-BY-4.0 obliges
// a distributor to indicate modifications, and the modifications are exactly
// what the manifest records. A hand-written file would drift from the tool the
// first time a texture cap changed, and would drift silently, because nothing
// reads it.
func renderAttribution(assets []asset) string {
	var out strings.Builder

	out.WriteString(`# Attribution

Every model under ` + "`assets/`" + ` is vendored from the Khronos
[glTF Sample Assets](` + upstreamURL + `) repository, each pinned to the commit
that last touched it. That repository has no releases and no tags, so a commit
SHA is the only pin that names specific bytes.

**Licence policy: CC0-1.0 and CC-BY-4.0 only.** No NonCommercial, no
NoDerivatives, no custom ` + "`LicenseRef`" + ` agreement. These examples are collected
for publication alongside the engine, which makes them a distribution, and a
committed reference screenshot is itself a derivative - so a
permissive-for-vendored, anything-for-fetched split would be a trap that only
sprang at publication.

**Baked-in trademarks are allowed** and recorded below per asset. A legal-mark
entry reserves the right to withdraw a *mark*; it does not qualify the licence
beside it.

**Every asset here is modified.** At a minimum it is repacked as a single
` + "`.glb`" + `, and two are resampled to fit; each entry states what was done to it.

This file is generated by ` + "`cmd/prepare-assets`" + ` from the manifest in that
command. Edit the manifest, then re-run the tool - do not edit this file.

## The set

| Asset | Licence | Files |
| --- | --- | --- |
`)

	for _, a := range assets {
		files := make([]string, 0, len(a.Outputs))
		for _, out := range a.Outputs {
			files = append(files, "`"+out.File+"`")
		}
		fmt.Fprintf(&out, "| [%s](#%s) | %s | %s |\n",
			a.Title, anchor(a.Title), strings.Join(spdxOf(a), ", "), strings.Join(files, ", "))
	}
	fmt.Fprintf(&out, "| [Truncated box](#truncated-box) | `CC0-1.0` | `broken/%s` |\n", brokenSource.File)

	out.WriteString("\n## Licences in use\n\n")
	for _, spdx := range usedSPDX(assets) {
		fmt.Fprintf(&out, "- `%s` - [%s](%s)\n", spdx, spdxName(assets, spdx), licenseURL[spdx])
	}

	for _, a := range assets {
		renderAsset(&out, a)
	}
	renderBroken(&out, assets)
	return out.String()
}

func renderAsset(out *strings.Builder, a asset) {
	fmt.Fprintf(out, "\n## %s\n\n", a.Title)
	fmt.Fprintf(out, "%s\n\n", a.Summary)
	fmt.Fprintf(out, "*In the set for:* %s\n\n", a.Why)
	fmt.Fprintf(out, "- **Source:** [`Models/%s` @ `%s`](%s/tree/%s/Models/%s) (`%s`)\n",
		a.Name, short(a.Commit), upstreamURL, a.Commit, a.Name, upstreamRepo)

	fmt.Fprintf(out, "- **Vendored as:**\n")
	for _, output := range a.Outputs {
		line := fmt.Sprintf("  - `assets/%s/%s`, packed from the `%s` variant", a.Name, output.File, output.Variant)
		if output.Note != "" {
			line += " - " + output.Note
		}
		fmt.Fprintln(out, line)
	}

	fmt.Fprintf(out, "- **Licence:**\n")
	for _, entry := range a.Legal {
		if entry.IsMark() {
			fmt.Fprintf(out, "  - *Legal mark*, %s: [%s](%s), %s, %s. Reserves the mark, not the licence.\n",
				entry.What, entry.Text, entry.URL, entry.Owner, entry.Year)
			continue
		}
		fmt.Fprintf(out, "  - %s: `%s` - [%s](%s)\n", entry.What, entry.SPDX, entry.Text, entry.URL)
	}

	if lines := attributionLines(a); len(lines) > 0 {
		fmt.Fprintf(out, "- **Required attribution:**\n")
		for _, line := range lines {
			fmt.Fprintf(out, "  - %s\n", line)
		}
	}

	fmt.Fprintf(out, "- **Modifications:** %s\n", modifications(a))
}

// attributionLines are the credits CC-BY-4.0 obliges this distribution to
// carry. A CC0 part needs none, so it produces none: a courtesy credit that
// looks like an obligation makes the real obligations harder to see.
func attributionLines(a asset) []string {
	var lines []string
	for _, entry := range a.Legal {
		if entry.IsMark() || entry.SPDX != "CC-BY-4.0" {
			continue
		}
		what := ""
		if !strings.EqualFold(entry.What, "everything") {
			what = fmt.Sprintf(" (%s)", entry.What)
		}
		lines = append(lines, fmt.Sprintf("%q%s by %s, %s, %s - licensed under [%s](%s), modified.",
			a.Title, what, entry.Artist, entry.Owner, entry.Year, entry.SPDX, entry.URL))
	}
	return lines
}

// modifications states what this tool did to an asset. CC-BY-4.0 obliges a
// distributor to indicate modifications, and every asset here is modified, so
// this is an obligation rather than a courtesy.
func modifications(a asset) string {
	var caps []int
	for _, output := range a.Outputs {
		if output.MaxTexture > 0 && !slices.Contains(caps, output.MaxTexture) {
			caps = append(caps, output.MaxTexture)
		}
	}
	slices.Sort(caps)

	parts := []string{"repacked as a single `.glb`, with every buffer and image in the binary chunk"}
	for _, size := range caps {
		parts = append(parts, fmt.Sprintf("images larger than %d px resampled to fit, keeping their media type", size))
	}
	parts = append(parts, "no geometry, material, animation or node data changed")
	return strings.Join(parts, "; ") + "."
}

func renderBroken(out *strings.Builder, assets []asset) {
	source, _ := find(assets, brokenSource.Asset)
	fmt.Fprintf(out, "\n## Truncated box\n\n")
	fmt.Fprintf(out, "`assets/broken/%s` is a deliberately corrupt file: the packed %s `.glb`\n"+
		"with its binary chunk cut in half, and both length fields left declaring the\n"+
		"bytes that are no longer there.\n\n", brokenSource.File, source.Title)
	fmt.Fprintf(out, "*In the set for:* it is the only asset that makes a load *fail*. A model that\n"+
		"fails is skipped, never substituted, and without a file that fails, nothing ever\n"+
		"demonstrates that. It also fails asynchronously - the header parses - which is\n"+
		"the case a missing path cannot cover.\n\n")
	fmt.Fprintf(out, "- **Source:** derived from %s, above\n", source.Title)
	fmt.Fprintf(out, "- **Licence:** `CC0-1.0`, inherited\n")
	fmt.Fprintf(out, "- **Modifications:** packed as a `.glb`, then truncated mid-chunk\n")
	fmt.Fprintf(out, "\nIt is CC0 by choice. A deliberately corrupted derivative is a poor thing to owe\nan attribution line for.\n")
}

func spdxOf(a asset) []string {
	seen := map[string]bool{}
	var out []string
	for _, entry := range a.Legal {
		if entry.IsMark() {
			if !seen["mark"] {
				seen["mark"] = true
				out = append(out, "+ legal mark")
			}
			continue
		}
		if !seen[entry.SPDX] {
			seen[entry.SPDX] = true
			out = append(out, "`"+entry.SPDX+"`")
		}
	}
	return out
}

func usedSPDX(assets []asset) []string {
	seen := map[string]bool{}
	var out []string
	for _, a := range assets {
		for _, entry := range a.Legal {
			if entry.IsMark() || seen[entry.SPDX] {
				continue
			}
			seen[entry.SPDX] = true
			out = append(out, entry.SPDX)
		}
	}
	slices.Sort(out)
	return out
}

func spdxName(assets []asset, spdx string) string {
	for _, a := range assets {
		for _, entry := range a.Legal {
			if entry.SPDX == spdx {
				return entry.Text
			}
		}
	}
	return spdx
}

func short(commit string) string {
	if len(commit) > 10 {
		return commit[:10]
	}
	return commit
}

// anchor is GitHub's heading-to-fragment rule, for the summary table's links.
func anchor(title string) string {
	var out strings.Builder
	for _, r := range strings.ToLower(title) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
			out.WriteRune(r)
		case r == ' ':
			out.WriteByte('-')
		}
	}
	return out.String()
}
